[package]
name = "whirl"
version = "0.1.0"
authors = ["Lars Frogner <lars_frogner@hotmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.2"
nalgebra = "0.21.0"

[workspace]
members = ["python-whirl"]
